version: '3.8'

services:
  webhook:
    container_name: webhook-tilda-webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      - PORT=3000
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/serviceAccountKey.json
    volumes:
      - ./serviceAccountKey.json:/usr/src/app/serviceAccountKey.json

networks:
  my_network:
    external: true