version: '3.8'

services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/serviceAccountKey.json
    command: node index.js