version: '3'

services:
  webhook:
    container_name: webhook-tilda-webhook
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network

networks:
  my_network:
    external: true